services:
  backbone:
    build:
      context: .
      target: backbone
    networks:
      mynet:
        ipv4_address: 172.28.5.2
  server:
     build:
       context: .
       target: server
     environment:
       - TRUSTED_PEERS=/ip4/172.28.5.2/tcp/9000/p2p/QmeMMaJCua1NMtiCzYVbYkvaFoVUaRsuo8jX18SfK6CdyB
     depends_on:
       - backbone
     restart: unless-stopped
     networks:
       - mynet
     deploy:
       replicas: 7
  malicious_server:
    build:
      context: .
      target: malicious_server
    depends_on:
      - backbone
    restart: unless-stopped
    networks:
      - mynet
    deploy:
      replicas: 1
  client:
    build:
      context: .
      target: client
    depends_on:
      - backbone
      - server
      #malicious_server
    restart: unless-stopped
    networks:
      - mynet
  trusted_server:
    build:
      context: .
      target: trusted_server
    depends_on:
      - backbone
    restart: unless-stopped
    networks:
      mynet:
        ipv4_address: 172.28.5.3
    deploy:
      replicas: 1

networks:
  mynet:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
